// SPDX-FileCopyrightText: The Quotient Project Contributors
// SPDX-License-Identifier: LGPL-3.0-or-later

#pragma once

#include "avatar.h"
#include "quotient_common.h"
#include "uri.h"

#include <QtCore/QObject>
#include <QtQmlIntegration/qqmlintegration.h>

namespace Quotient {
class Room;
class RoomMemberEvent;

//! \brief Snapshot of a user's state in a room at a point in time
//!
//! The class is a read-only value type that stores member data captured at
//! construction. It is designed to provide the data in a format ready for
//! visualizing a user (avatar or name) in the context of the room it was
//! generated in.
//!
//! \note RoomMemberSnapshot is not intended for interacting with the user's
//!       profile. Use Connection::user() for that to obtain a User object that
//!       has the support functions for modifying profile information.
//! \warning RoomMemberSnapshot is a value class and should not be kept between syncs.
//!          It does not track changes of the member state therefore some member changes
//!          (i.e. leaving the room) may render a RoomMemberSnapshot dangling, when
//!          calling any of its methods leads to undefined behaviour.
//! \sa User
class QUOTIENT_API RoomMemberSnapshot {
    Q_GADGET
    QML_NAMED_ELEMENT(roomMemberSnapshot)
    QML_UNCREATABLE("")

    Q_PROPERTY(bool isEmpty READ isEmpty CONSTANT)
    Q_PROPERTY(QString id READ id CONSTANT)
    Q_PROPERTY(Uri uri READ uri CONSTANT)
    Q_PROPERTY(bool isLocalMember READ isLocalMember CONSTANT)
    Q_PROPERTY(QString displayName READ displayName CONSTANT)
    Q_PROPERTY(QString htmlSafeDisplayName READ htmlSafeDisplayName CONSTANT)
    Q_PROPERTY(QString fullName READ fullName CONSTANT)
    Q_PROPERTY(QString htmlSafeFullName READ htmlSafeFullName CONSTANT)
    Q_PROPERTY(QString disambiguatedName READ disambiguatedName CONSTANT)
    Q_PROPERTY(QString htmlSafeDisambiguatedName READ htmlSafeDisambiguatedName CONSTANT)
    Q_PROPERTY(int hue READ hue CONSTANT)
    Q_PROPERTY(qreal hueF READ hueF CONSTANT)
    Q_PROPERTY(QColor color READ color CONSTANT)
    Q_PROPERTY(QUrl avatarUrl READ avatarUrl CONSTANT)
    Q_PROPERTY(int powerLevel READ powerLevel CONSTANT)

public:
    RoomMemberSnapshot() = default;

    explicit RoomMemberSnapshot(const Room* room, const RoomMemberEvent* member);

    bool isEmpty() const { return _memberId.isEmpty(); }

    bool operator==(const RoomMemberSnapshot& other) const { return id() == other.id(); }

    //! @brief Get unique stable user id
    //!
    //! The Matrix user ID is generated by the server and is never changed.
    QString id() const { return _memberId; }

    //! @brief The matrix.to URI for the user
    //!
    //! Typically used when you want to visit a user (see
    //! Quotient::UriResolverBase::visitResource()).
    //!
    //! \sa Quotient::UriResolverBase::visitResource()
    Uri uri() const;

    bool isLocalMember() const;

    Membership membershipState() const { return _membership; }

    //! \brief The raw unmodified display name for the user in the given room
    //!
    //! The value will be empty if no display name has been set.
    //!
    //! \warning This value is not sanitized or HTML escape so use appropriately.
    //!          For ready to display values use displayName() or fullName() for
    //!          plain text and htmlSafeDisplayName() or htmlSafeFullName() for
    //!          rich text.
    //!
    //! \sa displayName(), htmlSafeDisplayName(), fullName(), htmlSafeFullName()
    QString name() const { return _displayName; }

    //! \brief Get the user display name ready for display
    //!
    //! This function always aims to return something that can be displayed in a
    //! UI, so if no display name is set the user's Matrix ID will be returned.
    //!
    //! The output is sanitized and suitable for a plain text field. For a rich
    //! field use htmlSafeDisplayName().
    //!
    //! \sa htmlSafeDisplayName()
    QString displayName() const;

    //! \brief Get the user display name ready for display
    //!
    //! This function always aims to return something that can be displayed in a
    //! UI, so if no display name is set the user's Matrix ID will be returned.
    //!
    //! The output is sanitized and html escaped ready for a rich text field. For
    //! a plain field use displayName().
    //!
    //! \sa displayName()
    QString htmlSafeDisplayName() const { return displayName().toHtmlEscaped(); }

    //! \brief Get user name and id in a single string
    //!
    //! This function always aims to return something that can be displayed in a
    //! UI, so if no display name is set the just user's Matrix ID will be returned.
    //! The constructed string follows the format 'name (id)' which the spec
    //! recommends for users disambiguation in a room context and in other places.
    //!
    //! The output is sanitized and suitable for a plain text field. For a rich
    //! field use htmlSafeFullName().
    //!
    //! \sa htmlSafeFullName()
    QString fullName() const;

    //! \brief Get user name and id in a single string
    //!
    //! This function always aims to return something that can be displayed in a
    //! UI, so if no display name is set the just user's Matrix ID will be returned.
    //! The constructed string follows the format 'name (id)' which the spec
    //! recommends for users disambiguation in a room context and in other places.
    //!
    //! The output is sanitized and html escaped ready for a rich text field. For
    //! a plain field use fullName().
    //!
    //! \sa fullName()
    QString htmlSafeFullName() const { return fullName().toHtmlEscaped(); }

    //! \brief Get the disambiguated user name
    //!
    //! This function always aims to return something that can be displayed in a
    //! UI, so if no display name is set the just user's Matrix ID will be returned.
    //! The output is equivalent to fullName() if there is another user in the room
    //! with the same name. Otherwise it is equivalent to displayName().
    //!
    //! The output is sanitized and suitable for a plain text field. For a rich
    //! field use htmlSafeDisambiguatedName().
    //!
    //! \sa htmlSafeDisambiguatedName(), fullName(), displayName()
    QString disambiguatedName() const;

    //! \brief Get the disambiguated user name
    //!
    //! This function always aims to return something that can be displayed in a
    //! UI, so if no display name is set the just user's Matrix ID will be returned.
    //! The output is equivalent to htmlSafeFullName() if there is another user in the room
    //! with the same name. Otherwise it is equivalent to htmlSafeDisplayName().
    //!
    //! The output is sanitized and html escaped ready for a rich text field. For
    //! a plain field use disambiguatedName().
    //!
    //! \sa disambiguatedName(), htmlSafeFullName(), htmlSafeDisplayName()
    QString htmlSafeDisambiguatedName() const { return disambiguatedName().toHtmlEscaped(); }

    //! \brief Check whether the name or id of the member contains a substring
    //!
    //! This is useful for a predicate to filter room members.
    //! \sa MemberMatcher
    Q_INVOKABLE bool matches(QStringView substr, Qt::CaseSensitivity cs = Qt::CaseSensitive) const;

    //! \brief Hue color component of this user based on the user's Matrix ID
    //!
    //! The implementation is based on XEP-0392:
    //! https://xmpp.org/extensions/xep-0392.html
    int hue() const { return static_cast<int>(hueF() * 359); }

    //! \brief HueF color component of this user based on the user's Matrix ID
    //!
    //! The implementation is based on XEP-0392:
    //! https://xmpp.org/extensions/xep-0392.html
    qreal hueF() const { return _hueF; }

    //! \brief Color based on the user's Matrix ID
    //!
    //! See https://github.com/quotient-im/libQuotient/wiki/User-color-coding-standard-draft-proposal
    QColor color() const;

    const Avatar& avatarObject() const;

    //! \brief The mxc URL as a string for the user avatar in the room
    QString avatarMediaId() const { return isEmpty() ? QString() : _avatarMediaId.toString(); }

    //! \brief The mxc URL for the user avatar in the room
    QUrl avatarUrl() const;

    QImage avatar(int width, int height, Avatar::get_callback_t callback) const;

    QImage avatar(int dimension, Avatar::get_callback_t callback) const;

    //! \brief The power level of the member.
    //!
    //! This is in the context of the current room.
    int powerLevel() const { return _powerLevel; }

private:
    const Room* _room = nullptr;
    QString _memberId{};
    QString _displayName{};
    QUrl _avatarMediaId{};
    qreal _hueF = 0;
    int _powerLevel = std::numeric_limits<int>::min();
    Membership _membership = Membership::Undefined;
};

//! \brief A factory to get a functional object matching room members against a substring
//!
//! This is a convenience wrapper to use RoomMemberSnapshot::matches() in standard algorithms.
inline auto memberMatcher(auto substr, Qt::CaseSensitivity cs = Qt::CaseSensitive)
{
#ifdef __cpp_lib_bind_back
    return std::bind_back(&RoomMemberSnapshot::matches, substr, cs);
#else
    return [substr, cs](const RoomMemberSnapshot& m) { return m.matches(substr, cs); };
#endif
}

struct QUOTIENT_API MemberSorter {
    bool operator()(const RoomMemberSnapshot& u1, const RoomMemberSnapshot& u2) const
    {
        return operator()(u1.displayName(), u2.displayName());
    }
    bool operator()(QStringView u1name, QStringView u2name) const;
};

} // namespace Quotient
